In [55]:
class LR :

    def __init__ (self):
         self.m = None
         self.b = None
    
    def fit(self,X_train,y_train):
          num = 0 
          den = 0 

          for i in range(X_train.shape[0]):
                num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
                den = den + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))

          self.m = num/den
          self.b = y_train.mean() - (self.m * X_train.mean())

          print(self.m)
          print(self.b)
    
    def predict(self,X_test):
         return self.m * X_test + self.b
    
    


In [43]:
import numpy as np 
import pandas as pd


In [44]:
df =  pd.read_csv('placement.csv')

In [45]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [46]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values

In [47]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=2)

In [51]:
lr  = LR()


In [52]:
lr.fit(X_train,y_train)

1.0
-3.9860000000000007


8.58

In [53]:
lr.predict(X_test[0])

4.593999999999999

In [57]:
from sklearn.linear_model import LinearRegression

In [61]:
lrR = LinearRegression()
lrR.fit(X_train.reshape(-1,1),y_train.reshape(-1,1))


LinearRegression()

In [64]:
lrR.intercept_

array([-0.89611192])

In [65]:
lrR.coef_

array([[0.55795197]])

In [63]:
lrR.predict(X_test[0].reshape(-1,1))

array([[3.89111601]])