In [1]:
import numpy as np 

In [3]:
A = np.array([[1,1,1],[1,1,0], [1,0,0]])

In [5]:
Q,R = np.linalg.qr(A)

In [6]:
Q

array([[-5.77350269e-01, -4.08248290e-01, -7.07106781e-01],
       [-5.77350269e-01, -4.08248290e-01,  7.07106781e-01],
       [-5.77350269e-01,  8.16496581e-01,  5.55111512e-17]])

In [7]:
R

array([[-1.73205081, -1.15470054, -0.57735027],
       [ 0.        , -0.81649658, -0.40824829],
       [ 0.        ,  0.        , -0.70710678]])

In [9]:
Q_T = np.transpose(Q)

In [15]:
Q_T

array([[-5.77350269e-01, -5.77350269e-01, -5.77350269e-01],
       [-4.08248290e-01, -4.08248290e-01,  8.16496581e-01],
       [-7.07106781e-01,  7.07106781e-01,  5.55111512e-17]])

In [13]:
I = np.matmul(Q,Q_T)

In [16]:
I

array([[ 1.00000000e+00,  1.01465364e-17, -1.38419845e-17],
       [ 1.01465364e-17,  1.00000000e+00, -1.61960688e-16],
       [-1.38419845e-17, -1.61960688e-16,  1.00000000e+00]])

In [27]:
np.linalg.norm( - A)

2.23606797749979

In [17]:
def QR_factorization(A):
     Q_transpose  = np.array(gram_schmidt(A.T))
     R = Q_transpose.A
     Q = Q_transpose.T
     return Q,R


In [18]:
Q,R = QR_factorization(A)

NameError: name 'gram_schmidt' is not defined